services:
    setono_sylius_items_sold.block_event_listener.admin.product.update.tab_details.products_sold:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@SetonoSyliusItemsSoldPlugin/block/productOrders.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.product.update.tab_details, method: onBlockEvent }

    setono_sylius_items_sold.block_event_listener.admin.product_variant.update.tab_details.products_sold:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@SetonoSyliusItemsSoldPlugin/block/productVariantOrders.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.product_variant.update.tab_details, method: onBlockEvent }

    setono_sylius_items_sold.controller.default:
        class: Setono\SyliusItemsSoldPlugin\Controller\DefaultController
        public: true
